#ifndef CONFIG_H
#define CONFIG_H

#define BM_ROBOT_NUMBER 1

#if BM_ROBOT_NUMBER == 1
    #define WHEEL_DIAM_INCHES 2.6
#elif BM_ROBOT_NUMBER == 2
    #define WHEEL_DIAM_INCHES 4.9
#endif

#define MOVEMENT_TIME_BEFORE_SETTLE_CHECK_MS 500

#define STRAIGHT_DRIVE_SETTLE_COUNT 12
#define STRAIGHT_DRIVE_SETTLE_DEG_THRESHOLD 5.0

#define TURN_DRIVE_SETTLE_COUNT 12
#define TURN_DRIVE_SETTLE_HEADING_THRESHOLD 0.35

#endif