#ifndef CONFIG_H
#define CONFIG_H

#define WHEEL_DIAM_INCHES 2.75

#define STRAIGHT_DRIVE_SETTLE_COUNT 12
#define STRAIGHT_DRIVE_SETTLE_DEG_THRESHOLD 5.0

#define TURN_DRIVE_SETTLE_COUNT 12
#define TURN_DRIVE_SETTLE_HEADING_THRESHOLD 0.35

#define STRAIGHT_DRIVE_MIN_SPEED 0
#define PIPELINE_DRIVE_SETTLE_COUNT 12
#define PIPELINE_DRIVE_SETTLE_DEG_THRESHOLD 5.0

#endif